default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: nopass
  port: 5432

development:
  <<: *default
  database: LabForTest_development

test:
  <<: *default
  database: LabForTest_test

production:
  <<: *default
  database: LabForTest_production
  username: LabForTest
  password: <%= ENV['LABFORTEST_DATABASE_PASSWORD'] %>
